[phases.setup]
nixPkgs = ["python312", "libGL", "glib"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python attendance_face_only.py"
