[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "libGL", "glib"]

[phases.install]
cmds = [
  "python -m pip install --break-system-packages -r requirements.txt"
]

[start]
cmd = "python attendance_face_only.py"
