[phases.setup]
nixPkgs = [
  "python311",
  "libglvnd",
  "glib",
  "xorg.libX11",
  "xorg.libXext",
  "xorg.libXrender",
  "xorg.libSM"
]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/python attendance_face_only.py"
